version: '3.8'

services:
  finshark-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ./api:/app
    restart: always
